SELECT MFISEQUEN as ID,
MFIDOC,mfiloja,MFILOCAL,MFISERIE,
MFIREGISTRO,
MFIEMISSAO,
MFICLIENTE,MFICF,MFIEST,MFISITRIB,
MFIFILIAL,MFILOJA,MFILOCAL,
MFIITEM,MFICOD,MFIQUANT,MFIPRCVEN,MFITOTAL

MFICLASFIS
,MFIDELETE

,MFISITRIB

  FROM MFI010 order by MFISEQUEN desc

  select * from MFI010 order by MFISEQUEN desc
  