SELECT mfaprefixo, MFATIPO as tpNF, MFAFILIAL, * FROM MFA010 where mfadoc = 252 --AND MFAFILIAL = '02'  order by MFAEMISSAO desc
SELECT mfiserie, MFISEQUEN as SEQuencia,mfidoc as doc, MFINUMSEQ, MFISITRIB , mficlasfis, MFIDOC, MFICLIENTE, * FROM MFI010 where MFIDOC = 252
SELECT sum(MFIQUANT*MFIPRCVEN) FROM MFI010 where MFIDOC = 252
SELECT E1_NUMNOTA, * FROM SE1010 where e1_numnota = 252 --and E1_FILIAL = '02'
--select * from MFTCLASFISTRI where MFTCODIGO = 15 or MFTCODIGO = 17 or MFTCODIGO = 12 or MFTCODIGO = 16
--SELECT MFISEQUEN as SEQuencia, MFINUMSEQ, MFISITRIB , mficlasfis, MFIDOC as NUMR_NOTA, MFICLIENTE, * FROM MFI010 where mficf = '1202' order by MFIEMISSAO desc