--USE [megasim]
GO

/****** Object:  Table [dbo].[ALIQUOTA_UF]    Script Date: 25/04/2019 17:14:23 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[ALIQUOTA_UF](
	[CFOPUF_ID] [bigint] NULL,
	[CST_ICMS] [nvarchar](3) NULL,
	[ALIQUOTA_ICMS_DENTRO] [int] NOT NULL,
	[ALIQUOTA_ICMS_FORA] [int] NOT NULL,
	[CST_PIS] [nvarchar](3) NULL,
	[ALIQUOTA_PIS] [float] NULL,
	[CST_COFINS] [nvarchar](3) NULL,
	[ALIQUOTA_COFINS] [float] NULL,
	[PERC_BASE_REDUZ] [float] NULL,
	[CST_ORIG_ICMS] [int] NULL
) ON [PRIMARY]

GO

ALTER TABLE [dbo].[ALIQUOTA_UF]  WITH CHECK ADD  CONSTRAINT [FK_ALIQUOTA_UF_CFOPUF] FOREIGN KEY([CFOPUF_ID])
REFERENCES [dbo].[CFOPUF] ([CFOPUF_ID])
GO

ALTER TABLE [dbo].[ALIQUOTA_UF] CHECK CONSTRAINT [FK_ALIQUOTA_UF_CFOPUF]
GO


