ALTER procedure spCLIENTE @Acao int, @CLIENTE_ID bigint, @PESSOA_ID bigint, @ESTABELECIMENTO_ID INT, @VENDEDOR_ID bigint, @TIPO_CLIENTE INT, @CGCCPF nvarchar(14)
									 , @NOME nvarchar(100), @RAZAO_SOCIAL nvarchar(100), @DT_NASC datetime, @DT_CAD datetime, @STATUS nvarchar(1), @SEXO nvarchar(1)
									 , @CONTATO nvarchar(70), @REGIAO int, @ORIGEM nvarchar(2), @LIMITE_CREDITO float, @ESTRANGEIRO bit, @CPFFUNCCONVENIO varchar(14)
									 , @PERC_DESC_CONVENIO int, @OBS nvarchar(MAX), @CODG_SUFRAMA bigint
as  begin
	if (@Acao = 1) begin			--incluir registro
		BEGIN TRANSACTION
			SET @CLIENTE_ID = (select max(CLIENTE_ID) from CLIENTE) + 1

			IF @CLIENTE_ID IS NULL 
				SET @CLIENTE_ID = 1
			IF @CLIENTE_ID <= 0 
				SET @CLIENTE_ID = 1

			INSERT INTO CLIENTE (CLIENTE_ID,PESSOA_ID,ESTABELECIMENTO_ID,VENDEDOR_ID,TIPO_CLIENTE
								 ,CGCCPF,NOME,RAZAO_SOCIAL,DT_NASC,DT_CAD,STATUS,SEXO,CONTATO
								 ,REGIAO,ORIGEM,LIMITE_CREDITO,ESTRANGEIRO,CPFFUNCCONVENIO
								 ,PERC_DESC_CONVENIO,OBS,CODG_SUFRAMA)
			Values (@CLIENTE_ID,@PESSOA_ID,@ESTABELECIMENTO_ID,@VENDEDOR_ID,@TIPO_CLIENTE
					,@CGCCPF,@NOME,@RAZAO_SOCIAL,@DT_NASC,@DT_CAD,@STATUS,@SEXO,@CONTATO
					,@REGIAO,@ORIGEM,@LIMITE_CREDITO,@ESTRANGEIRO,@CPFFUNCCONVENIO
					,@PERC_DESC_CONVENIO,@OBS,@CODG_SUFRAMA)

		IF @@ERROR <> 0 
		   ROLLBACK 
		   ELSE
		      COMMIT
	End
	else if (@Acao = 2) begin       --alterar registro
		BEGIN TRANSACTION

			update CLIENTE SET PESSOA_ID=@PESSOA_ID,VENDEDOR_ID=@VENDEDOR_ID,TIPO_CLIENTE=@TIPO_CLIENTE
					,CGCCPF=@CGCCPF,NOME=@NOME,RAZAO_SOCIAL=@RAZAO_SOCIAL,DT_NASC=@DT_NASC,DT_CAD=@DT_CAD
					,STATUS=@STATUS,SEXO=@SEXO,CONTATO=@CONTATO,REGIAO=@REGIAO,ORIGEM=@ORIGEM,LIMITE_CREDITO=@LIMITE_CREDITO
					,ESTRANGEIRO=@ESTRANGEIRO,CPFFUNCCONVENIO=@CPFFUNCCONVENIO,PERC_DESC_CONVENIO=@PERC_DESC_CONVENIO
					,OBS=@OBS,CODG_SUFRAMA=@CODG_SUFRAMA
			where CLIENTE_ID = @CLIENTE_ID

		IF @@ERROR <> 0 
		   ROLLBACK 
		   ELSE
		      COMMIT
	End
	else if (@Acao = 3) begin       --excluir registro
		BEGIN TRANSACTION

			delete from CLIENTE where CLIENTE_ID = @CLIENTE_ID

		IF @@ERROR <> 0 
		   ROLLBACK 
		   ELSE
		      COMMIT
	End
	begin raiserror('Erro, não executado, spCLIENTE',14,1)     
	End
End