ALTER procedure spFAMILIAPRODUTO @Acao int, @FAMILIAPRODUTO_ID bigint, @CODG_FAMILIA nvarchar(10), @DESCRICAO nvarchar(60), @UNIDADE_MEDIDA nvarchar(4), @DESC_UNIDADE_MEDIDA nvarchar(50), @PRODUCAO bit, @PERC_COMPOE_VENDA float
as  begin
	if (@Acao = 1) begin
		BEGIN TRANSACTION
			SET @FAMILIAPRODUTO_ID = (select max(FAMILIAPRODUTO_ID) from FAMILIAPRODUTO) + 1

			IF @FAMILIAPRODUTO_ID IS NULL 
				SET @FAMILIAPRODUTO_ID = 1
			IF @FAMILIAPRODUTO_ID <= 0 
				SET @FAMILIAPRODUTO_ID = 1

			INSERT INTO FAMILIAPRODUTO (FAMILIAPRODUTO_ID,CODG_FAMILIA,DESCRICAO,UNIDADE_MEDIDA,DESC_UNIDADE_MEDIDA,PRODUCAO,PERC_COMPOE_VENDA)
			Values (@FAMILIAPRODUTO_ID, @CODG_FAMILIA, @DESCRICAO, @UNIDADE_MEDIDA, @DESC_UNIDADE_MEDIDA, @PRODUCAO,@PERC_COMPOE_VENDA)

		IF @@ERROR <> 0 
		   ROLLBACK 
		   ELSE
		      COMMIT
	End     
	else if (@Acao = 2) begin        
		BEGIN TRANSACTION
			update FAMILIAPRODUTO SET DESCRICAO=@DESCRICAO, UNIDADE_MEDIDA=@UNIDADE_MEDIDA, DESC_UNIDADE_MEDIDA=@DESC_UNIDADE_MEDIDA, PRODUCAO=@PRODUCAO, PERC_COMPOE_VENDA=@PERC_COMPOE_VENDA
			where FAMILIAPRODUTO_ID = @FAMILIAPRODUTO_ID     

		IF @@ERROR <> 0 
		   ROLLBACK 
		   ELSE
		      COMMIT
	End     
	else if (@Acao = 3) begin        
		BEGIN TRANSACTION
			delete from FAMILIAPRODUTO where FAMILIAPRODUTO_ID = @FAMILIAPRODUTO_ID     

		IF @@ERROR <> 0 
		   ROLLBACK 
		   ELSE
		      COMMIT
	End     
	begin raiserror('Erro, não executado, FAMILIAPRODUTO',14,1)     
	End  
End 