ALTER procedure spNFITEM @Acao int, @NF_ID int, @SEQ_ID bigint, @PRODUTO_ID bigint, @VALOR float, @DESCONTO float,
					  @QTDE float, @CFOP_ID nvarchar(10), @STRIBUTARIA nvarchar(4), @VLRBASEICMS float, @PERCICMS real,
					  @VLRICMS float, @VLRBASEICMSSUBST float, @PERCICMSSUBST float, @VLRICMSSUBST float, @PERCREDUCAOICMS real,
					  @PERCIVA real, @PERC_IPI real
as  begin
	if (@Acao = 1) begin
		BEGIN TRANSACTION

			INSERT INTO NFITEM (NF_ID,SEQ_ID,PRODUTO_ID,VALOR,DESCONTO,
							QTDE,CFOP_ID,STRIBUTARIA,VLRBASEICMS,PERCICMS,
							VLRICMS,VLRBASEICMSSUBST,PERCICMSSUBST,VLRICMSSUBST,PERCREDUCAOICMS,
							PERCIVA,PERC_IPI)
			Values (@NF_ID,@SEQ_ID,@PRODUTO_ID,@VALOR,@DESCONTO,
					@QTDE,@CFOP_ID,@STRIBUTARIA,@VLRBASEICMS,@PERCICMS,
					@VLRICMS,@VLRBASEICMSSUBST,@PERCICMSSUBST,@VLRICMSSUBST,@PERCREDUCAOICMS,
					@PERCIVA,@PERC_IPI)

		IF @@ERROR <> 0 
		   ROLLBACK 
		   ELSE
		      COMMIT
	End     
	else if (@Acao = 2) begin        
		BEGIN TRANSACTION
			update NFITEM SET 
					PRODUTO_ID=@PRODUTO_ID,VALOR=@VALOR,DESCONTO=@DESCONTO,
					QTDE=@QTDE,CFOP_ID=@CFOP_ID,STRIBUTARIA=@STRIBUTARIA,VLRBASEICMS=@VLRBASEICMS,
					PERCICMS=@PERCICMS,VLRICMS=@VLRICMS,VLRBASEICMSSUBST=@VLRBASEICMSSUBST,PERCICMSSUBST=@PERCICMSSUBST,
					VLRICMSSUBST=@VLRICMSSUBST,PERCREDUCAOICMS=@PERCREDUCAOICMS,PERCIVA=@PERCIVA,
					PERC_IPI=@PERC_IPI
			where NF_ID = @NF_ID
			 and seq_id = @SEQ_ID

		IF @@ERROR <> 0 
		   ROLLBACK 
		   ELSE
		      COMMIT
	End     
	else if (@Acao = 3) begin        
		BEGIN TRANSACTION
			delete from NFITEM
			where NF_ID = @NF_ID
			 and seq_id = @SEQ_ID

		IF @@ERROR <> 0 
		   ROLLBACK 
		   ELSE
		      COMMIT
	End     
	begin raiserror('Erro, não executado, spNFITEM',14,1)     
	End  
End 