alter procedure spPEDIDOFATURA  @Acao int, @PEDIDOFATURA_ID bigint, @PEDIDO_ID bigint, @TABELAPRECO_ID int, @FORMAPAGTO_ID int, @TIPOVENDA_ID int
as  begin
	if (@Acao = 1) begin
		BEGIN TRANSACTION
			SET @PEDIDOFATURA_ID = (select max(PEDIDOFATURA_ID) from PEDIDOFATURA) + 1

			IF @PEDIDOFATURA_ID IS NULL 
				SET @PEDIDOFATURA_ID = 1
			IF @PEDIDOFATURA_ID <= 0 
				SET @PEDIDOFATURA_ID = 1

			INSERT INTO PEDIDOFATURA (PEDIDOFATURA_ID,PEDIDO_ID,TABELAPRECO_ID,FORMAPAGTO_ID,TIPOVENDA_ID)
			Values (@PEDIDOFATURA_ID,@PEDIDO_ID,@TABELAPRECO_ID,@FORMAPAGTO_ID,@TIPOVENDA_ID)

		IF @@ERROR <> 0 
		   ROLLBACK 
		   ELSE
		      COMMIT
	End     
	else if (@Acao = 2) begin        
		BEGIN TRANSACTION
			update PEDIDOFATURA SET TIPOVENDA_ID=@TIPOVENDA_ID,FORMAPAGTO_ID=@FORMAPAGTO_ID,TABELAPRECO_ID=@TABELAPRECO_ID
			where PEDIDO_ID = @PEDIDO_ID

		IF @@ERROR <> 0 
		   ROLLBACK 
		   ELSE
		      COMMIT
	End     
	else if (@Acao = 3) begin        
		BEGIN TRANSACTION
			delete from PEDIDOFATURA where PEDIDOFATURA_ID = @PEDIDOFATURA_ID     

		IF @@ERROR <> 0 
		   ROLLBACK 
		   ELSE
		      COMMIT
	End     
	begin raiserror('Erro, não executado, spPEDIDOFATURA',14,1)     
	End  
End 