ALTER procedure spPRODUTO @Acao int, @PRODUTO_ID bigint, @EMPRESA_ID int, @CODG_PRODUTO nvarchar(100), @FORNECEDOR_ID int, @DESCRICAO varchar(max),
									  @REFERENCIA nvarchar(MAX), @FAMILIAPRODUTO_ID bigint, @UNIDADE_MEDIDA nvarchar(10), @CODG_BARRA nvarchar(MAX), @SITUACAO nvarchar(1),
									  @SITUACAO_TRIBUTARIA nvarchar(80), @ALIQUOTA_ICMS float, @PERC_DESCONTO int, @TIPO_PROD int, @CODG_NCM nvarchar(8),
									  @COMP_TRIBUTARIA int, @PRECO_CUSTO_ANTERIOR float, @qtd_ped_anterior float, @PRECO_CUSTO float, @PRECO_ATACADO float,
									  @PRECO_Venda float, @PERCIVA float, @DT_CADASTRO datetime, @PERC_COMIS float, @PATH_IMAGEM varchar(MAX), @ORIGEM_MERCADO int,
									  @LOCACAO varchar(MAX), @PRECO_VAREJO_ANTERIOR float, @PRECO_ATACADO_ANTERIOR float, @EMBALAGEM int, @USUARIO_ID int, 
									  @QTD_MINIMO float, @QTD_MAXIMO float, @DT_ULT_VENDA datetime, @DT_ULT_COMPRA datetime, @PESO_LIQUIDO float, @PESO_BRUTO float,
									  @TAMANHO bigint, @MARCA_ID bigint, @PRODUTO_BALANCA bit, @PERMITE_DESCONTO bit, @CONCEDER_PRODUCAO bit, @PERC_COMPOE_VENDA float
as  begin
	if (@Acao = 1) begin
		BEGIN TRANSACTION
			SET @PRODUTO_ID = (select max(PRODUTO_ID) from PRODUTO) + 1

			IF @PRODUTO_ID IS NULL 
				SET @PRODUTO_ID = 1
			IF @PRODUTO_ID <= 0 
				SET @PRODUTO_ID = 1

			INSERT INTO PRODUTO (PRODUTO_ID,EMPRESA_ID,CODG_PRODUTO,FORNECEDOR_ID,DESCRICAO,
								 REFERENCIA,FAMILIAPRODUTO_ID,UNIDADE_MEDIDA,CODG_BARRA,SITUACAO,
								 SITUACAO_TRIBUTARIA,ALIQUOTA_ICMS,PERC_DESCONTO,TIPO_PROD,CODG_NCM,
								 COMP_TRIBUTARIA,PRECO_CUSTO_ANTERIOR,qtd_ped_anterior,PRECO_CUSTO,
								 PRECO_ATACADO,PRECO_Venda,PERCIVA,DT_CADASTRO,PERC_COMIS,PATH_IMAGEM,
								 ORIGEM_MERCADO,LOCACAO,PRECO_VAREJO_ANTERIOR,PRECO_ATACADO_ANTERIOR,
								 EMBALAGEM,USUARIO_ID,QTD_MINIMO,QTD_MAXIMO,DT_ULT_VENDA,DT_ULT_COMPRA,
								 PESO_LIQUIDO,PESO_BRUTO,TAMANHO,MARCA_ID,PRODUTO_BALANCA,PERMITE_DESCONTO,
								 CONCEDER_PRODUCAO,PERC_COMPOE_VENDA)
			Values				(@PRODUTO_ID,@EMPRESA_ID,@CODG_PRODUTO,@FORNECEDOR_ID,@DESCRICAO,
								 @REFERENCIA,@FAMILIAPRODUTO_ID,@UNIDADE_MEDIDA,@CODG_BARRA,@SITUACAO,
								 @SITUACAO_TRIBUTARIA,@ALIQUOTA_ICMS,@PERC_DESCONTO,@TIPO_PROD,@CODG_NCM,
								 @COMP_TRIBUTARIA,@PRECO_CUSTO_ANTERIOR,@qtd_ped_anterior,@PRECO_CUSTO,
								 @PRECO_ATACADO,@PRECO_Venda,@PERCIVA,@DT_CADASTRO,@PERC_COMIS,@PATH_IMAGEM,
								 @ORIGEM_MERCADO,@LOCACAO,@PRECO_VAREJO_ANTERIOR,@PRECO_ATACADO_ANTERIOR,
								 @EMBALAGEM,@USUARIO_ID,@QTD_MINIMO,@QTD_MAXIMO,@DT_ULT_VENDA,@DT_ULT_COMPRA,
								 @PESO_LIQUIDO,@PESO_BRUTO,@TAMANHO,@MARCA_ID,@PRODUTO_BALANCA,@PERMITE_DESCONTO,
								 @CONCEDER_PRODUCAO,@PERC_COMPOE_VENDA)

		IF @@ERROR <> 0 
		   ROLLBACK 
		   ELSE
		      COMMIT
	End     
	else if (@Acao = 2) begin        
		BEGIN TRANSACTION
			update PRODUTO SET   FORNECEDOR_ID=@FORNECEDOR_ID,DESCRICAO=@DESCRICAO,REFERENCIA=@REFERENCIA,
								 FAMILIAPRODUTO_ID=@FAMILIAPRODUTO_ID,UNIDADE_MEDIDA=@UNIDADE_MEDIDA,CODG_BARRA=@CODG_BARRA,
								 SITUACAO=@SITUACAO,SITUACAO_TRIBUTARIA=@SITUACAO_TRIBUTARIA,ALIQUOTA_ICMS=@ALIQUOTA_ICMS,
								 PERC_DESCONTO=@PERC_DESCONTO,TIPO_PROD=@TIPO_PROD,CODG_NCM=@CODG_NCM,
								 COMP_TRIBUTARIA=@COMP_TRIBUTARIA,PRECO_CUSTO_ANTERIOR=@PRECO_CUSTO_ANTERIOR,qtd_ped_anterior=@qtd_ped_anterior,
								 PRECO_CUSTO=@PRECO_CUSTO,PRECO_ATACADO=@PRECO_ATACADO,PRECO_Venda=@PRECO_Venda,PERCIVA=@PERCIVA,
								 DT_CADASTRO=@DT_CADASTRO,PERC_COMIS=@PERC_COMIS,PATH_IMAGEM=@PATH_IMAGEM,ORIGEM_MERCADO=@ORIGEM_MERCADO,
								 LOCACAO=@LOCACAO,PRECO_VAREJO_ANTERIOR=@PRECO_VAREJO_ANTERIOR,PRECO_ATACADO_ANTERIOR=@PRECO_ATACADO_ANTERIOR,
								 EMBALAGEM=@EMBALAGEM,USUARIO_ID=@USUARIO_ID,QTD_MINIMO=@QTD_MINIMO,QTD_MAXIMO=@QTD_MAXIMO,
								 DT_ULT_VENDA=@DT_ULT_VENDA,DT_ULT_COMPRA=@DT_ULT_COMPRA,PESO_LIQUIDO=@PESO_LIQUIDO,PESO_BRUTO=@PESO_BRUTO,
								 TAMANHO=@TAMANHO,MARCA_ID=@MARCA_ID,PRODUTO_BALANCA=@PRODUTO_BALANCA,PERMITE_DESCONTO=@PERMITE_DESCONTO,
								 CONCEDER_PRODUCAO=@CONCEDER_PRODUCAO,PERC_COMPOE_VENDA=@PERC_COMPOE_VENDA
			where PRODUTO_ID = @PRODUTO_ID     

		IF @@ERROR <> 0 
		   ROLLBACK 
		   ELSE
		      COMMIT
	End     
	else if (@Acao = 3) begin        
		BEGIN TRANSACTION
			delete from PRODUTO where PRODUTO_ID = @PRODUTO_ID     

		IF @@ERROR <> 0 
		   ROLLBACK 
		   ELSE
		      COMMIT
	End     
	begin raiserror('Erro, não executado, spPRODUTO',14,1)     
	End  
End 