
/****** Object:  Table [dbo].[COMANDAITEM]    Script Date: 12/01/2019 16:38:15 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[COMANDAITEM](
	[COMANDA_ID] [bigint] NOT NULL,
	[SEQ_ID] [bigint] NOT NULL,
	[PRODUTO_ID] [bigint] NOT NULL,
	[QTDE] [float] NOT NULL,
	[VALOR_ITEM] [float] NOT NULL,
	[SITUACAO] [nvarchar](10) NULL,
	[USUARIO_ID] [int] NULL,
 CONSTRAINT [pk_COMANDAITEM] PRIMARY KEY CLUSTERED 
(
	[COMANDA_ID] ASC,
	[SEQ_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

ALTER TABLE [dbo].[COMANDAITEM]  WITH CHECK ADD  CONSTRAINT [FK_COMANDAITEM_COMANDA] FOREIGN KEY([COMANDA_ID])
REFERENCES [dbo].[COMANDA] ([COMANDA_ID])
GO

ALTER TABLE [dbo].[COMANDAITEM] CHECK CONSTRAINT [FK_COMANDAITEM_COMANDA]
GO

ALTER TABLE [dbo].[COMANDAITEM]  WITH CHECK ADD  CONSTRAINT [FK_COMANDAITEM_PRODUTO] FOREIGN KEY([PRODUTO_ID])
REFERENCES [dbo].[PRODUTO] ([PRODUTO_ID])
GO

ALTER TABLE [dbo].[COMANDAITEM] CHECK CONSTRAINT [FK_COMANDAITEM_PRODUTO]
GO

ALTER TABLE [dbo].[COMANDAITEM]  WITH CHECK ADD  CONSTRAINT [FK_COMANDAITEM_USUARIO] FOREIGN KEY([USUARIO_ID])
REFERENCES [dbo].[USUARIO] ([USUARIO_ID])
GO

ALTER TABLE [dbo].[COMANDAITEM] CHECK CONSTRAINT [FK_COMANDAITEM_USUARIO]
GO


