
/****** Object:  Table [dbo].[COMANDA]    Script Date: 12/01/2019 16:36:37 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[COMANDA](
	[COMANDA_ID] [bigint] NOT NULL,
	[CARTAOBARRA_ID] [bigint] NOT NULL,
	[USUARIO_ID] [int] NOT NULL,
	[DT_REGISTRO] [datetime] NOT NULL,
	[SITUACAO] [nvarchar](10) NOT NULL,
 CONSTRAINT [PK_COMANDA] PRIMARY KEY CLUSTERED 
(
	[COMANDA_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

ALTER TABLE [dbo].[COMANDA]  WITH CHECK ADD  CONSTRAINT [FK_COMANDA_CARTAOBARRA] FOREIGN KEY([CARTAOBARRA_ID])
REFERENCES [dbo].[CARTAOBARRA] ([CARTAOBARRA_ID])
GO

ALTER TABLE [dbo].[COMANDA] CHECK CONSTRAINT [FK_COMANDA_CARTAOBARRA]
GO

ALTER TABLE [dbo].[COMANDA]  WITH CHECK ADD  CONSTRAINT [FK_COMANDA_USUARIO] FOREIGN KEY([USUARIO_ID])
REFERENCES [dbo].[USUARIO] ([USUARIO_ID])
GO

ALTER TABLE [dbo].[COMANDA] CHECK CONSTRAINT [FK_COMANDA_USUARIO]
GO


