--USE [MEGASIM]
GO

/****** Object:  Table [dbo].[OSVEICEQP]    Script Date: 29/07/2019 11:20:40 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[OSVEICEQP](
	[OS_ID] [bigint] NOT NULL,
	[VEICULO_ID] [bigint] NULL,
	[EQUIPAMENTO_ID] [bigint] NULL
) ON [PRIMARY]

GO

ALTER TABLE [dbo].[OSVEICEQP]  WITH CHECK ADD  CONSTRAINT [FK_OSVEICEQP_OS] FOREIGN KEY([OS_ID])
REFERENCES [dbo].[OS] ([OS_ID])
GO

ALTER TABLE [dbo].[OSVEICEQP] CHECK CONSTRAINT [FK_OSVEICEQP_OS]
GO

ALTER TABLE [dbo].[OSVEICEQP]  WITH CHECK ADD  CONSTRAINT [FK_OSVEICEQP_OSEQUIPAMENTO] FOREIGN KEY([EQUIPAMENTO_ID])
REFERENCES [dbo].[OSEQUIPAMENTO] ([EQUIPAMENTO_ID])
GO

ALTER TABLE [dbo].[OSVEICEQP] CHECK CONSTRAINT [FK_OSVEICEQP_OSEQUIPAMENTO]
GO

ALTER TABLE [dbo].[OSVEICEQP]  WITH CHECK ADD  CONSTRAINT [FK_OSVEICEQP_OSVEICULO] FOREIGN KEY([VEICULO_ID])
REFERENCES [dbo].[OSVEICULO] ([VEICULO_ID])
GO

ALTER TABLE [dbo].[OSVEICEQP] CHECK CONSTRAINT [FK_OSVEICEQP_OSVEICULO]
GO


