--USE [MEGASIM]
GO

/****** Object:  Table [dbo].[PEDIDONF]    Script Date: 10/09/2019 17:56:51 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[PEDIDONF](
	[PEDIDONF_ID] [bigint] NOT NULL,
	[PEDIDO_ID] [bigint] NOT NULL,
	[NF_ID] [bigint] NOT NULL,
 CONSTRAINT [PK_PEDIDONF] PRIMARY KEY CLUSTERED 
(
	[PEDIDONF_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[PEDIDONF]  WITH CHECK ADD  CONSTRAINT [FK_PEDIDONF_NF] FOREIGN KEY([NF_ID])
REFERENCES [dbo].[NF] ([NF_ID])
GO

ALTER TABLE [dbo].[PEDIDONF] CHECK CONSTRAINT [FK_PEDIDONF_NF]
GO

ALTER TABLE [dbo].[PEDIDONF]  WITH CHECK ADD  CONSTRAINT [FK_PEDIDONF_PEDIDO] FOREIGN KEY([PEDIDO_ID])
REFERENCES [dbo].[PEDIDO] ([PEDIDO_ID])
GO

ALTER TABLE [dbo].[PEDIDONF] CHECK CONSTRAINT [FK_PEDIDONF_PEDIDO]
GO


