CREATE TRIGGER TGR_PEDIDO_PEDIDOFATURA
ON PEDIDO
FOR INSERT
AS
BEGIN
    DECLARE
    --@VALOR  DECIMAL(10,2),
    --@DATA   DATETIME
	@PEDIDOFATURA_ID	BIGINT,
	@PEDIDO_ID			BIGINT,
	@TABELAPRECO_ID		BIGINT,
	@FORMAPAGTO_ID		BIGINT,
	@TIPOVENDA_ID		BIGINT

	SET @PEDIDOFATURA_ID = (select max(PEDIDOFATURA_ID) from PEDIDOFATURA) + 1

	IF @PEDIDOFATURA_ID IS NULL 
		SET @PEDIDOFATURA_ID = 1
	IF @PEDIDOFATURA_ID <= 0 
		SET @PEDIDOFATURA_ID = 1

    SELECT  PEDIDOFATURA_ID = @PEDIDOFATURA_ID,
			PEDIDO_ID = @PEDIDO_ID,
			TABELAPRECO_ID = @TABELAPRECO_ID,
			FORMAPAGTO_ID = @FORMAPAGTO_ID,
			TIPOVENDA_ID = @TIPOVENDA_ID
	FROM INSERTED
 
    UPDATE PEDIDOFATURA SET 

			PEDIDOFATURA_ID = @PEDIDOFATURA_ID,
			PEDIDO_ID = @PEDIDO_ID,
			TABELAPRECO_ID = @TABELAPRECO_ID,
			FORMAPAGTO_ID = @FORMAPAGTO_ID,
			TIPOVENDA_ID = @TIPOVENDA_ID

	SALDO_FINAL = SALDO_FINAL + @VALOR

    WHERE PEDIDO_ID = @PEDIDO_ID
END
GO

/****** Script do comando SelectTopNRows de SSMS  ******/
SELECT TOP (1000) [PEDIDOFATURA_ID]
      ,[PEDIDO_ID]
      ,[TABELAPRECO_ID]
      ,[FORMAPAGTO_ID]
      ,[TIPOVENDA_ID]
  FROM [SHFINFO].[dbo].[PEDIDOFATURA]

/****** Script do comando SelectTopNRows de SSMS  ******/
SELECT TOP (1000) [PEDIDO_ID]
      ,[ESTABELECIMENTO_ID]
      ,[EMPRESA_ID]
      ,[CLIENTE_ID]
      ,[VENDEDOR_ID]
      ,[USUARIO_ID]
      ,[CARTAOBARRA_ID]
      ,[USUARIO_LIBERA_VENDA]
      ,[NUMERO_CAIXA_CPU]
      ,[CGCCPF]
      ,[DT_REQ]
      ,[STATUS]
      ,[TIPO_REGISTRO]
      ,[VALOR_DESCONTO]
      ,[PERC_DESC]
      ,[NOME_CLIENTE]
      ,[VALOR_RECEBIDO]
      ,[VALOR_TOTAL]
      ,[PREFIXO]
  FROM [SHFINFO].[dbo].[PEDIDO]