--USE [MEGASIM]
GO

DROP VIEW vwVeiculo

/****** Object:  View [dbo].[vwVeiculo]    Script Date: 29/07/2019 11:24:46 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE VIEW [dbo].[vwVeiculo] AS  select OSVEICULO.*, PESSOA.CNPJCPF, PESSOA.DESCRICAO AS DescPessoa, PESSOA.RAZAO, PESSOA.SITUACAO FROM PESSOA WITH (NOLOCK)  INNER JOIN OSVEICULO WITH (NOLOCK)  ON PESSOA.PESSOA_ID = OSVEICULO.PESSOA_ID
GO


