
CREATE TABLE [dbo].[MP](
	[PRODUTO_ID_PA] [bigint] NOT NULL,
	[PRODUTO_ID_MP] [bigint] NOT NULL,
	[VALOR] [float] NOT NULL,
	[QTDE] [float] NOT NULL,
 CONSTRAINT [PK_MP] PRIMARY KEY CLUSTERED 
(
	[PRODUTO_ID_PA] ASC,
	[PRODUTO_ID_MP] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

ALTER TABLE [dbo].[MP]  WITH CHECK ADD  CONSTRAINT [FK_MP_PRODUTO] FOREIGN KEY([PRODUTO_ID_PA])
REFERENCES [dbo].[PRODUTO] ([PRODUTO_ID])
GO

ALTER TABLE [dbo].[MP] CHECK CONSTRAINT [FK_MP_PRODUTO]
GO

ALTER TABLE [dbo].[MP]  WITH CHECK ADD  CONSTRAINT [FK_MP_PRODUTO1] FOREIGN KEY([PRODUTO_ID_MP])
REFERENCES [dbo].[PRODUTO] ([PRODUTO_ID])
GO

ALTER TABLE [dbo].[MP] CHECK CONSTRAINT [FK_MP_PRODUTO1]
GO


