USE [master]
GO

/****** Object:  Database [SHSSYS]    Script Date: 01/31/2014 12:17:18 ******/
CREATE DATABASE [SHSSYS] ON  PRIMARY 
( NAME = N'MEGASIM', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL10_50.SQLEXPRESS\MSSQL\DATA\SHSSYS.mdf' , SIZE = 37888KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'MEGASIM_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL10_50.SQLEXPRESS\MSSQL\DATA\SHSSYS_log.ldf' , SIZE = 35712KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [SHSSYS] SET COMPATIBILITY_LEVEL = 100
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [SHSSYS].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [SHSSYS] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [SHSSYS] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [SHSSYS] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [SHSSYS] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [SHSSYS] SET ARITHABORT OFF 
GO

ALTER DATABASE [SHSSYS] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [SHSSYS] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [SHSSYS] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [SHSSYS] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [SHSSYS] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [SHSSYS] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [SHSSYS] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [SHSSYS] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [SHSSYS] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [SHSSYS] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [SHSSYS] SET  DISABLE_BROKER 
GO

ALTER DATABASE [SHSSYS] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [SHSSYS] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [SHSSYS] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [SHSSYS] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [SHSSYS] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [SHSSYS] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [SHSSYS] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [SHSSYS] SET  READ_WRITE 
GO

ALTER DATABASE [SHSSYS] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [SHSSYS] SET  MULTI_USER 
GO

ALTER DATABASE [SHSSYS] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [SHSSYS] SET DB_CHAINING OFF 
GO


