USE [MEGASIM]
GO

/****** Object:  Table [dbo].[ESTOQUEFORNECEDOR]    Script Date: 28/04/2017 16:35:15 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[ESTOQUEFORNECEDOR](
	[FORNECEDOR_ID] [bigint] NULL,
	[PRODUTO_ID] [bigint] NULL,
	[ESTABELECIMENTO_ID] [int] NULL
) ON [PRIMARY]

GO


