DELETE FROM ITEMREQ
DELETE FROM CABECAREQ
DELETE FROM CAIXADIAITEM
DELETE FROM CAIXADIA
DELETE FROM CAIXATESORARIAitem
DELETE FROM CAIXATESORARIA
DELETE FROM CHEQUE
DELETE FROM ITEMLANCAMENTO
DELETE FROM ENDERECO
DELETE FROM ERRO
DELETE FROM FONE
DELETE FROM FORNECEDOR
DELETE FROM IE
DELETE FROM IM
DELETE FROM NOTAENTRADAITEM
DELETE FROM ITEMRECEBIMENTO
DELETE FROM LANCAMENTO
DELETE FROM NFITEM
DELETE FROM NF
DELETE FROM NOTAENTRADA
DELETE FROM CLIENTE
DELETE FROM COMISSAOITEM
DELETE FROM COMISSAO
DELETE FROM CONTA
DELETE FROM CONTACORRENTE
DELETE FROM CUPOM
DELETE FROM EMAIL
DELETE FROM EMPRESAACESSO WHERE USUARIO_ID <> 144
DELETE FROM EMPRESAPARAMETRO
DELETE FROM VENDEDOR WHERE VENDEDOR_ID <> 0
DELETE FROM EQUIPE WHERE CODG_EQ <> 1
DELETE FROM FAMILIAPRODUTO
DELETE FROM PRODUTO
DELETE FROM IMPRESSORA
DELETE FROM INDICE
DELETE FROM INVENTARIO
DELETE FROM ITEMRECEBIMENTO
DELETE FROM OBS
DELETE FROM RG
DELETE FROM PERMISSAO WHERE USUID <> 144
DELETE FROM USUARIO WHERE USUARIO_ID <> 144
DELETE FROM TRANSPORTADORA