use loja
SELECT NOTAENTRADA.DT_ENTRADA,    NOTAENTRADA.NUMR_NOTA, NOTAENTRADA.CODG_USU, NOTAENTRADA.STATUS, ITEMNOTAENTRADA.CODG_PROD, ITEMNOTAENTRADA.QTD_ENTRADA, 
                      ITEMNOTAENTRADA.STATUS AS Expr1
FROM         NOTAENTRADA INNER JOIN
                      ITEMNOTAENTRADA ON NOTAENTRADA.EMPRESA_ID = ITEMNOTAENTRADA.EMPRESA_ID AND NOTAENTRADA.ENTRADA_ID = ITEMNOTAENTRADA.ENTRADA_ID
where CODG_PROD = 4652

SELECT SUM(ITEMNOTAENTRADA.qtd_entrada) as tot_entrada
FROM         NOTAENTRADA INNER JOIN
                      ITEMNOTAENTRADA ON NOTAENTRADA.EMPRESA_ID = ITEMNOTAENTRADA.EMPRESA_ID AND NOTAENTRADA.ENTRADA_ID = ITEMNOTAENTRADA.ENTRADA_ID
where CODG_PROD = 4652