insert into megasim.dbo.pedidovaca(PEDIDO_ID,CLIENTE_ID,EMPRESA_ID,CGCCPF,USUARIO_ID,VENDEDOR_ID,TIPOVENDA_ID
								   ,DT_REQ,STATUS,TIPO_REGISTRO,USUARIO_LIBERA_VENDA,VALOR_DESCONTO,PERC_DESC
								   ,NOME_CLIENTE,VALOR_RECEBIDO,VALOR_TOTAL,NUMERO_CAIXA_CPU,ESTABELECIMENTO_ID
								   ,CARTAOBARRA_ID,TABELAPRECO_ID,PREFIXO) 
select PEDIDO_ID,CLIENTE_ID,EMPRESA_ID,CGCCPF,USUARIO_ID,VENDEDOR_ID,TIPOVENDA_ID
								   ,DT_REQ,STATUS,TIPO_REGISTRO,USUARIO_LIBERA_VENDA,VALOR_DESCONTO,PERC_DESC
								   ,NOME_CLIENTE,VALOR_RECEBIDO,VALOR_TOTAL,NUMERO_CAIXA_CPU,ESTABELECIMENTO_ID
								   ,CARTAOBARRA_ID,TABELAPRECO_ID,PREFIXO from teste.dbo.pedido