USE [GLOBAL]
GO

/****** Object:  StoredProcedure [dbo].[eUpdateCliente]    Script Date: 01/15/2012 12:01:33 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE [dbo].[spUpdateCliente]
	   @REGISTRO		int	OUT,
	   @A1_CGC VARCHAR(14) = NULL,
	   @A1_FILIAL VARCHAR(02),
	   @A1_COD VARCHAR(06) = NULL,
	   @A1_LOJA VARCHAR(02) = NULL,
	   @A1_NOME VARCHAR(70) = NULL,
	   @A1_PESSOA VARCHAR(1) = NULL,
	   @A1_NREDUZ VARCHAR(45) = NULL,
	   @A1_TIPO VARCHAR(1) = NULL,
	   @A1_END VARCHAR(60) = NULL,
	   @A1_MUN VARCHAR(30) = NULL,
	   @A1_EST VARCHAR(02) = NULL ,     
	   @A1_BAIRRO VARCHAR(40) = NULL,
	   @A1_ESTADO VARCHAR(20) = NULL,
	   @A1_CEP VARCHAR(8) = NULL,
	   @A1_DDI VARCHAR(6) = NULL,
	   @A1_DDD VARCHAR(3) = NULL,
	   @A1_TEL VARCHAR(15) = NULL,
	   @A1_TELEX VARCHAR(10) = NULL,
	   @A1_FAX VARCHAR(15) = NULL,      
	   @A1_CONTATO VARCHAR(15) = NULL,
	   @A1_INSCR VARCHAR(18) = NULL,
	   @A1_INSCRM VARCHAR(18) = NULL,
	   @A1_PFISICA VARCHAR(18) = NULL,
	   @A1_RG VARCHAR(15) = NULL,
	   @A1_EMAIL VARCHAR(60) = NULL,
	   @A1_HPAGE VARCHAR(60) = NULL ,    
	   @A1_INSCRUR VARCHAR(18) = NULL,	   
	   @A1_CODCIDADE int = null,
	   @A1_NUMERO VARCHAR(60) = NULL
        	
AS

BEGIN TRANSACTION

Declare @Utimoregistro int
DECLARE @Ultimo VARCHAR(6)
DECLARE @WULTIMO VARCHAR(6)
DECLARE @WZERO VARCHAR(6)

   UPDATE [dbo].[SA1010]
   SET 
	   A1_FILIAL = @A1_FILIAL
	   ,A1_COD = @A1_COD
	   ,A1_LOJA = @A1_LOJA
	   ,A1_NOME = @A1_NOME 
	   ,A1_PESSOA = @A1_PESSOA 
	   ,A1_NREDUZ = @A1_NREDUZ 
	   ,A1_TIPO = @A1_TIPO 
	   ,A1_END = @A1_END 
	   ,A1_MUN = @A1_MUN 
	   ,A1_EST = @A1_EST 
	   ,A1_BAIRRO = @A1_BAIRRO 
	   ,A1_ESTADO = @A1_ESTADO 
	   ,A1_CEP = @A1_CEP 
	   ,A1_DDI = @A1_DDI 
	   ,A1_DDD = @A1_DDD 
	   ,A1_TEL = @A1_TEL 
	   ,A1_TELEX = @A1_TELEX 
	   ,A1_FAX = @A1_FAX 
	   ,A1_CONTATO = @A1_CONTATO 
	   ,A1_INSCR = @A1_INSCR 
	   ,A1_INSCRM = @A1_INSCRM 
	   ,A1_PFISICA = @A1_PFISICA 
	   ,A1_RG = @A1_RG 
	   ,A1_EMAIL = @A1_EMAIL 
	   ,A1_HPAGE = @A1_HPAGE 
	   ,A1_INSCRUR = @A1_INSCRUR 
	   ,A1_CODCIDADE = @A1_CODCIDADE 
	   ,A1_NUMERO = @A1_NUMERO

 WHERE  A1_CGC = @A1_CGC

-- EXECUTE(@CONDICAO)
			
commit

GO