USE [MEGASIM]
GO

/****** Object:  Table [dbo].[CSON]    Script Date: 04/26/2012 06:53:24 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[CSON](
	[CODIGO] [nvarchar](3) NOT NULL,
	[DESCRICAO] [nvarchar](max) NOT NULL,
	[OBS] [nvarchar](max) NULL,
 CONSTRAINT [PK_TRIBUTACAO_CSON] PRIMARY KEY CLUSTERED 
(
	[CODIGO] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO


