USE [MEGASIM]
GO

/****** Object:  Table [dbo].[CST]    Script Date: 04/26/2012 06:53:56 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[CST](
	[CODIGO] [nvarchar](3) NOT NULL,
	[DESCRICAO] [nvarchar](max) NOT NULL,
	[OBS] [nvarchar](max) NULL,
 CONSTRAINT [PK_TRIBUTACAO] PRIMARY KEY CLUSTERED 
(
	[CODIGO] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO


