CREATE VIEW dbo.viewConsultaFaturamento

AS
SELECT     EMPRESA.RAZAO_SOCIAL, ITEMLANCAMENTO.NUMR_DOC, ITEMLANCAMENTO.SEQ, ITEMLANCAMENTO.VALOR_ITEM, ITEMLANCAMENTO.STATUS, 
                      ITEMLANCAMENTO.DT_VENCIMENTO, ITEMLANCAMENTO.DT_BAIXA, ITEMLANCAMENTO.DT_CANCELA, ITEMLANCAMENTO.VALOR_DESCONTO, 
                      ITEMLANCAMENTO.NUMR_DP, TIPOVENDA.DESCRICAO, FORMAPAGTO.DESCRICAO AS Expr1, CLIENTE.CGCCPF, CLIENTE.NOME
FROM         TIPOVENDA INNER JOIN
                      LANCAMENTO INNER JOIN
                      ITEMLANCAMENTO ON LANCAMENTO.LANCAMENTO_ID = ITEMLANCAMENTO.LANCAMENTO_ID INNER JOIN
                      EMPRESA ON LANCAMENTO.EMPRESA_ID = EMPRESA.EMPRESA_ID INNER JOIN
                      CLIENTE ON LANCAMENTO.PROP = CLIENTE.CGCCPF ON TIPOVENDA.FORMA_ID = ITEMLANCAMENTO.FORMA_ID INNER JOIN
                      FORMAPAGTO ON TIPOVENDA.FORMA_ID = FORMAPAGTO.FORMA_ID
GO