CREATE VIEW vw_FATURAMENTO
AS 

SELECT     EMPRESA.CGC, EMPRESA.RAZAO_SOCIAL, EMPRESA.FONE, LANCAMENTO.TIPO_LANCAMENTO, LANCAMENTO.PROP, LANCAMENTO.DT_LANC, 
                      CLIENTE.NOME, ITEMLANCAMENTO.NUMR_DOC, ITEMLANCAMENTO.SEQ, ITEMLANCAMENTO.FORMA_ID, ITEMLANCAMENTO.VALOR_ITEM, 
                      ITEMLANCAMENTO.STATUS, ITEMLANCAMENTO.DT_VENCIMENTO, ITEMLANCAMENTO.DT_BAIXA, ITEMLANCAMENTO.DT_CANCELA, 
                      ITEMLANCAMENTO.VALOR_DESCONTO, ITEMLANCAMENTO.NUMR_DP
FROM         EMPRESA INNER JOIN
                      LANCAMENTO ON EMPRESA.EMPRESA_ID = LANCAMENTO.EMPRESA_ID INNER JOIN
                      CLIENTE ON LANCAMENTO.PROP = CLIENTE.CGCCPF INNER JOIN
                      ITEMLANCAMENTO ON LANCAMENTO.LANCAMENTO_ID = ITEMLANCAMENTO.LANCAMENTO_ID

GO  
