DELETE from EQUIPE 

DELETE from ENTRADAESTOQUEITEM 
DELETE FROM ENTRADAESTOQUE

DELETE from TRANSPORTADORACOMPRADOR
DELETE from TRANSPORTADORA

DELETE from PRODUCAOPERDA
DELETE from PRODUCAOPERDAVENDA
DELETE from PRODUTOLOTE
DELETE from PROGRAMA
DELETE from REGISTROPRODUCAOITEM
DELETE from REGISTROPRODUCAO
DELETE from TABELAPRECOITEM
DELETE from TABELAPRECO
DELETE from TABPRECOCOMISSAO
DELETE from TAXAMARKUP
DELETE from TIPOCLIENTE
DELETE from TIPOENTRADA
DELETE from TIPOVENDA
DELETE from TROCAPRODUTO
DELETE from turno
DELETE from VENDACUSTO

DELETE from FORMAPAGTO
DELETE from PRODUTOFORNECEDOR
DELETE from ESTOQUEFORNEC
DELETE from FORNECEDORCOMPRADOR
DELETE from FORNECEDOR
DELETE from ESTABELECIMENTOACESSO
DELETE from ESTABVENDEDOR
DELETE from evento
DELETE from CONTROLEPERDAITEM
DELETE from CONTROLEPERDA
DELETE from agencia
DELETE from banco
DELETE from BOLETO
DELETE from CARTAOBARRA
DELETE from CARTAOpedido

DELETE from menu
DELETE from PEDIDOCOMPRAITEM
DELETE from PEDIDOCOMPRA
DELETE from PEDIDOITEMOBS
DELETE from PEDIDOTEMP

DELETE from CCUSTO
DELETE from cheque
DELETE from CONTROLEPERDAITEM
DELETE from CONTROLEPERDA
DELETE from Endereco
DELETE from IMPREL
DELETE from IMPRESSORA
DELETE from Indice
DELETE from ESTOQUEFORNEC
DELETE from ESTOQUETRANSF
DELETE from POSICAOESTOQUE
DELETE from ESTOQUE
DELETE from PEDIDOITEM
DELETE from CUPOM
DELETE from ENTREGA
DELETE from PEDIDO
DELETE from CAIXADIAITEM
DELETE from CAIXADIA
DELETE from CAIXATESORARIAitem
DELETE from CAIXATESORARIA
DELETE from CHEQUE
DELETE from ITEMLANCAMENTO
DELETE from ENDERECO
DELETE from ERRO
DELETE from FONE
DELETE from FORNECEDOR
DELETE from IE
DELETE from IM
DELETE from NOTAENTRADAITEM
DELETE from ITEMLANCAMENTO
DELETE from LANCAMENTO
DELETE from NFITEM
DELETE from NF
DELETE from NOTAENTRADA
DELETE from CLIENTE
DELETE from CLIENTESALDO
DELETE from COMISSAOITEM
DELETE from COMISSAOPARAM
DELETE from COMISSAO
DELETE from CONTA
DELETE from CONTACORRENTE
DELETE from CUPOM
DELETE from EMAIL
DELETE from ESTABELECIMENTOACESSO
DELETE from VENDEDOR WHERE VENDEDOR_ID <> 0

DELETE from FAMILIAPRODUTO
         
DELETE from OSPECA
DELETE from OSSERVICO
DELETE from OSTAREFA
DELETE from VEICULO
DELETE from OS
DELETE from EQUIPAMENTO
DELETE from INVENTARIO
DELETE from PRODUTO
DELETE from IMPRESSORA
DELETE from INDICE

DELETE from vendedor
DELETE from OBS
DELETE from RG
DELETE from PERMISSAO
DELETE from USUARIO WHERE USUARIO_ID <> 144
DELETE from TRANSPORTADORA
DELETE from PESSOAENDERECO
DELETE from PESSOATIPO
DELETE from pessoa WHERE PESSOA_ID <> 1

